pre-push:
  parallel: true
  commands:
    lint:
      glob: "*.go"
      run: cd helpers && golangci-lint run && cd otel && golangci-lint run && cd ../sentry && golangci-lint run
    test:
      glob: "*.go"
      run: cd helpers/otel && go test -cover -race ./... && cd ../sentry && go test -cover -race ./...