// Code generated by gowrap. DO NOT EDIT.
// template: https://raw.githubusercontent.com/adlandh/gowrap-templates/main/sentry.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package main

//go:generate gowrap gen -p github.com/adlandh/gowrap-templates/examples/echo-sentry -i AppInterface -t https://raw.githubusercontent.com/adlandh/gowrap-templates/main/sentry.gotmpl -o aplication_sentry_gen.go -l ""

import (
	"context"
	"encoding/json"

	"github.com/getsentry/sentry-go"
)

// AppInterfaceWithSentry implements AppInterface interface instrumented with opentracing spans
type AppInterfaceWithSentry[T any] struct {
	AppInterface[T]
	_instance      string
	_spanDecorator func(span *sentry.Span, params, results map[string]interface{})
}

// NewAppInterfaceWithSentry returns AppInterfaceWithSentry
func NewAppInterfaceWithSentry[T any](base AppInterface[T], instance string, spanDecorator ...func(span *sentry.Span, params, results map[string]interface{})) AppInterfaceWithSentry[T] {
	d := AppInterfaceWithSentry[T]{
		AppInterface: base,
		_instance:    instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	} else {
		d._spanDecorator = d._defaultSpanDecorator
	}

	return d
}

func (_d AppInterfaceWithSentry[T]) _defaultSpanDecorator(span *sentry.Span, params, results map[string]interface{}) {
	for p := range params {
		switch params[p].(type) {
		case context.Context:
		default:
			val, _ := json.Marshal(params[p])
			span.SetTag("param."+p, string(val))
		}
	}

	for p := range results {
		switch results[p].(type) {
		case context.Context:
		default:
			val, _ := json.Marshal(results[p])
			span.SetTag("result."+p, string(val))
		}
	}
}

// GenFullGreeting implements AppInterface
func (_d AppInterfaceWithSentry[T]) GenFullGreeting(ctx context.Context, name T) (greeting T, err error) {
	span := sentry.StartSpan(ctx, _d._instance+".AppInterface.GenFullGreeting", sentry.TransactionName("AppInterface.GenFullGreeting"))
	ctx = span.Context()

	defer func() {
		_d._spanDecorator(span, map[string]interface{}{
			"ctx":  ctx,
			"name": name}, map[string]interface{}{
			"greeting": greeting,
			"err":      err})
		if err != nil {
			span.SetTag("event", "error")
			span.SetTag("message", err.Error())
		}

		span.Finish()
	}()
	return _d.AppInterface.GenFullGreeting(ctx, name)
}

// GetGreeting implements AppInterface
func (_d AppInterfaceWithSentry[T]) GetGreeting(ctx context.Context) (greeting T) {
	span := sentry.StartSpan(ctx, _d._instance+".AppInterface.GetGreeting", sentry.TransactionName("AppInterface.GetGreeting"))
	ctx = span.Context()

	defer func() {
		_d._spanDecorator(span, map[string]interface{}{
			"ctx": ctx}, map[string]interface{}{
			"greeting": greeting})
		span.Finish()
	}()
	return _d.AppInterface.GetGreeting(ctx)
}

// SetGreeting implements AppInterface
func (_d AppInterfaceWithSentry[T]) SetGreeting(ctx context.Context, greeting T) (err error) {
	span := sentry.StartSpan(ctx, _d._instance+".AppInterface.SetGreeting", sentry.TransactionName("AppInterface.SetGreeting"))
	ctx = span.Context()

	defer func() {
		_d._spanDecorator(span, map[string]interface{}{
			"ctx":      ctx,
			"greeting": greeting}, map[string]interface{}{
			"err": err})
		if err != nil {
			span.SetTag("event", "error")
			span.SetTag("message", err.Error())
		}

		span.Finish()
	}()
	return _d.AppInterface.SetGreeting(ctx, greeting)
}
