// Code generated by gowrap. DO NOT EDIT.
// template: https://raw.githubusercontent.com/adlandh/gowrap-templates/main/echo-otel.gotmpl
// gowrap: http://github.com/hexdigest/gowrap

package main

import (
	"github.com/labstack/echo/v4"

	helpers "github.com/adlandh/gowrap-templates/helpers/otel"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"
)

// ServerInterfaceWithTracing implements ServerInterface interface instrumented with opentracing spans
type ServerInterfaceWithTracing struct {
	ServerInterface
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
	_instance      string
}

// NewServerInterfaceWithTracing returns ServerInterfaceWithTracing
func NewServerInterfaceWithTracing(base ServerInterface, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) ServerInterfaceWithTracing {
	if instance == "" {
		instance = "handlers"
	}

	d := ServerInterfaceWithTracing{
		ServerInterface: base,
		_instance:       instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	} else {
		d._spanDecorator = helpers.SpanDecorator
	}

	return d
}

// DecorateServerInterfaceWithTracing returns ServerInterfaceWithTracing. Useful for uber fx
func DecorateServerInterfaceWithTracing(base ServerInterface) ServerInterfaceWithTracing {
	return NewServerInterfaceWithTracing(base, "")
}

// GetGreeting implements ServerInterface
func (_d ServerInterfaceWithTracing) GetGreeting(ctx echo.Context) (err error) {
	request := ctx.Request()
	ctxNew, _span := otel.Tracer(_d._instance).Start(request.Context(), "ServerInterface.GetGreeting")

	defer func() {
		_d._spanDecorator(_span, map[string]interface{}{
			"ctx": ctx}, map[string]interface{}{
			"err": err})
		_span.End()
	}()
	ctx.SetRequest(request.WithContext(ctxNew))
	return _d.ServerInterface.GetGreeting(ctx)
}

// GetHello implements ServerInterface
func (_d ServerInterfaceWithTracing) GetHello(ctx echo.Context, name string) (err error) {
	request := ctx.Request()
	ctxNew, _span := otel.Tracer(_d._instance).Start(request.Context(), "ServerInterface.GetHello")

	defer func() {
		_d._spanDecorator(_span, map[string]interface{}{
			"ctx":  ctx,
			"name": name}, map[string]interface{}{
			"err": err})
		_span.End()
	}()
	ctx.SetRequest(request.WithContext(ctxNew))
	return _d.ServerInterface.GetHello(ctx, name)
}

// SetGreeting implements ServerInterface
func (_d ServerInterfaceWithTracing) SetGreeting(ctx echo.Context, greeting string) (err error) {
	request := ctx.Request()
	ctxNew, _span := otel.Tracer(_d._instance).Start(request.Context(), "ServerInterface.SetGreeting")

	defer func() {
		_d._spanDecorator(_span, map[string]interface{}{
			"ctx":      ctx,
			"greeting": greeting}, map[string]interface{}{
			"err": err})
		_span.End()
	}()
	ctx.SetRequest(request.WithContext(ctxNew))
	return _d.ServerInterface.SetGreeting(ctx, greeting)
}
