name: "Test app"

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false

      - name: Pulling code
        uses: actions/checkout@v4

      - name: Run tests for otel helpers
        run: go test -race -coverprofile=../../coverage1.txt -covermode=atomic ./...
        with:
          working-directory: helpers/otel
      - name: Run tests for sentry helpers
        run: cd helpers/sentry && go test -race -coverprofile=../../coverage2.txt -covermode=atomic ./...
        with:
          working-directory: helpers/sentry

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage1.txt, ./coverage2.txt